; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -passes=pre-isel-intrinsic-lowering %s | FileCheck -check-prefix=OPT %s

; A memcpy that stages memory through LDS is expanded here rather than left to
; SelectionDAG, so that the accesses are exposed to scheduling. Only sizes that
; come out as a whole number of 16-byte accesses qualify: anything else leaves a
; residual tail of mismatched widths, which SelectionDAG handles better. memmove
; never qualifies -- expanding it costs an overlap check and a residual loop.

define amdgpu_kernel void @memcpy_global_to_lds_16(ptr addrspace(3) %dst, ptr addrspace(1) %src) {
; OPT-LABEL: define amdgpu_kernel void @memcpy_global_to_lds_16(
; OPT-SAME: ptr addrspace(3) [[DST:%.*]], ptr addrspace(1) [[SRC:%.*]]) {
; OPT-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[SRC]], i64 0
; OPT-NEXT:    [[TMP2:%.*]] = load <4 x i32>, ptr addrspace(1) [[TMP1]], align 16
; OPT-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i8, ptr addrspace(3) [[DST]], i64 0
; OPT-NEXT:    store <4 x i32> [[TMP2]], ptr addrspace(3) [[TMP3]], align 16
; OPT-NEXT:    ret void
;
  call void @llvm.memcpy.p3.p1.i64(ptr addrspace(3) align 16 %dst, ptr addrspace(1) align 16 %src, i64 16, i1 false)
  ret void
}

define amdgpu_kernel void @memcpy_lds_to_global_32(ptr addrspace(1) %dst, ptr addrspace(3) %src) {
; OPT-LABEL: define amdgpu_kernel void @memcpy_lds_to_global_32(
; OPT-SAME: ptr addrspace(1) [[DST:%.*]], ptr addrspace(3) [[SRC:%.*]]) {
; OPT-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i8, ptr addrspace(3) [[SRC]], i64 0
; OPT-NEXT:    [[TMP2:%.*]] = load <4 x i32>, ptr addrspace(3) [[TMP1]], align 16
; OPT-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[DST]], i64 0
; OPT-NEXT:    store <4 x i32> [[TMP2]], ptr addrspace(1) [[TMP3]], align 16
; OPT-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i8, ptr addrspace(3) [[SRC]], i64 16
; OPT-NEXT:    [[TMP5:%.*]] = load <4 x i32>, ptr addrspace(3) [[TMP4]], align 16
; OPT-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[DST]], i64 16
; OPT-NEXT:    store <4 x i32> [[TMP5]], ptr addrspace(1) [[TMP6]], align 16
; OPT-NEXT:    ret void
;
  call void @llvm.memcpy.p1.p3.i64(ptr addrspace(1) align 16 %dst, ptr addrspace(3) align 16 %src, i64 32, i1 false)
  ret void
}

; Not a whole number of 16-byte accesses: left alone.
define amdgpu_kernel void @memcpy_global_to_lds_31(ptr addrspace(3) %dst, ptr addrspace(1) %src) {
; OPT-LABEL: define amdgpu_kernel void @memcpy_global_to_lds_31(
; OPT-SAME: ptr addrspace(3) [[DST:%.*]], ptr addrspace(1) [[SRC:%.*]]) {
; OPT-NEXT:    call void @llvm.memcpy.p3.p1.i64(ptr addrspace(3) align 16 [[DST]], ptr addrspace(1) align 16 [[SRC]], i64 31, i1 false)
; OPT-NEXT:    ret void
;
  call void @llvm.memcpy.p3.p1.i64(ptr addrspace(3) align 16 %dst, ptr addrspace(1) align 16 %src, i64 31, i1 false)
  ret void
}

; At the loop-lowering width, so expanding would form a loop rather than a
; straight-line body: left alone.
define amdgpu_kernel void @memcpy_global_to_lds_256(ptr addrspace(3) %dst, ptr addrspace(1) %src) {
; OPT-LABEL: define amdgpu_kernel void @memcpy_global_to_lds_256(
; OPT-SAME: ptr addrspace(3) [[DST:%.*]], ptr addrspace(1) [[SRC:%.*]]) {
; OPT-NEXT:    call void @llvm.memcpy.p3.p1.i64(ptr addrspace(3) align 16 [[DST]], ptr addrspace(1) align 16 [[SRC]], i64 256, i1 false)
; OPT-NEXT:    ret void
;
  call void @llvm.memcpy.p3.p1.i64(ptr addrspace(3) align 16 %dst, ptr addrspace(1) align 16 %src, i64 256, i1 false)
  ret void
}

; Non-constant size: already governed by the size threshold.
define amdgpu_kernel void @memcpy_global_to_lds_variable(ptr addrspace(3) %dst, ptr addrspace(1) %src, i64 %n) {
; OPT-LABEL: define amdgpu_kernel void @memcpy_global_to_lds_variable(
; OPT-SAME: ptr addrspace(3) [[DST:%.*]], ptr addrspace(1) [[SRC:%.*]], i64 [[N:%.*]]) {
; OPT-NEXT:    [[TMP1:%.*]] = and i64 [[N]], 15
; OPT-NEXT:    [[TMP2:%.*]] = sub i64 [[N]], [[TMP1]]
; OPT-NEXT:    [[TMP3:%.*]] = icmp ne i64 [[TMP2]], 0
; OPT-NEXT:    br i1 [[TMP3]], label %[[DYNAMIC_MEMCPY_EXPANSION_MAIN_BODY:.*]], label %[[DYNAMIC_MEMCPY_EXPANSION_RESIDUAL_COND:.*]]
; OPT:       [[DYNAMIC_MEMCPY_EXPANSION_MAIN_BODY]]:
; OPT-NEXT:    [[LOOP_INDEX:%.*]] = phi i64 [ 0, [[TMP0:%.*]] ], [ [[TMP7:%.*]], %[[DYNAMIC_MEMCPY_EXPANSION_MAIN_BODY]] ]
; OPT-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[SRC]], i64 [[LOOP_INDEX]]
; OPT-NEXT:    [[TMP5:%.*]] = load <4 x i32>, ptr addrspace(1) [[TMP4]], align 16
; OPT-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i8, ptr addrspace(3) [[DST]], i64 [[LOOP_INDEX]]
; OPT-NEXT:    store <4 x i32> [[TMP5]], ptr addrspace(3) [[TMP6]], align 16
; OPT-NEXT:    [[TMP7]] = add i64 [[LOOP_INDEX]], 16
; OPT-NEXT:    [[TMP8:%.*]] = icmp ult i64 [[TMP7]], [[TMP2]]
; OPT-NEXT:    br i1 [[TMP8]], label %[[DYNAMIC_MEMCPY_EXPANSION_MAIN_BODY]], label %[[DYNAMIC_MEMCPY_EXPANSION_RESIDUAL_COND]]
; OPT:       [[DYNAMIC_MEMCPY_EXPANSION_RESIDUAL_COND]]:
; OPT-NEXT:    [[TMP9:%.*]] = icmp ne i64 [[TMP1]], 0
; OPT-NEXT:    br i1 [[TMP9]], label %[[DYNAMIC_MEMCPY_EXPANSION_RESIDUAL_BODY:.*]], label %[[DYNAMIC_MEMCPY_POST_EXPANSION:.*]]
; OPT:       [[DYNAMIC_MEMCPY_EXPANSION_RESIDUAL_BODY]]:
; OPT-NEXT:    [[RESIDUAL_LOOP_INDEX:%.*]] = phi i64 [ 0, %[[DYNAMIC_MEMCPY_EXPANSION_RESIDUAL_COND]] ], [ [[TMP14:%.*]], %[[DYNAMIC_MEMCPY_EXPANSION_RESIDUAL_BODY]] ]
; OPT-NEXT:    [[TMP10:%.*]] = add i64 [[TMP2]], [[RESIDUAL_LOOP_INDEX]]
; OPT-NEXT:    [[TMP11:%.*]] = getelementptr inbounds i8, ptr addrspace(1) [[SRC]], i64 [[TMP10]]
; OPT-NEXT:    [[TMP12:%.*]] = load i8, ptr addrspace(1) [[TMP11]], align 1
; OPT-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i8, ptr addrspace(3) [[DST]], i64 [[TMP10]]
; OPT-NEXT:    store i8 [[TMP12]], ptr addrspace(3) [[TMP13]], align 1
; OPT-NEXT:    [[TMP14]] = add i64 [[RESIDUAL_LOOP_INDEX]], 1
; OPT-NEXT:    [[TMP15:%.*]] = icmp ult i64 [[TMP14]], [[TMP1]]
; OPT-NEXT:    br i1 [[TMP15]], label %[[DYNAMIC_MEMCPY_EXPANSION_RESIDUAL_BODY]], label %[[DYNAMIC_MEMCPY_POST_EXPANSION]]
; OPT:       [[DYNAMIC_MEMCPY_POST_EXPANSION]]:
; OPT-NEXT:    ret void
;
  call void @llvm.memcpy.p3.p1.i64(ptr addrspace(3) align 16 %dst, ptr addrspace(1) align 16 %src, i64 %n, i1 false)
  ret void
}

; No LDS involved: unchanged by this rule.
define amdgpu_kernel void @memcpy_global_to_global_16(ptr addrspace(1) %dst, ptr addrspace(1) %src) {
; OPT-LABEL: define amdgpu_kernel void @memcpy_global_to_global_16(
; OPT-SAME: ptr addrspace(1) [[DST:%.*]], ptr addrspace(1) [[SRC:%.*]]) {
; OPT-NEXT:    call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) align 16 [[DST]], ptr addrspace(1) align 16 [[SRC]], i64 16, i1 false)
; OPT-NEXT:    ret void
;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) align 16 %dst, ptr addrspace(1) align 16 %src, i64 16, i1 false)
  ret void
}

; memmove and memset are never taken, whatever the address space.
define amdgpu_kernel void @memmove_global_to_lds_16(ptr addrspace(3) %dst, ptr addrspace(1) %src) {
; OPT-LABEL: define amdgpu_kernel void @memmove_global_to_lds_16(
; OPT-SAME: ptr addrspace(3) [[DST:%.*]], ptr addrspace(1) [[SRC:%.*]]) {
; OPT-NEXT:    call void @llvm.memmove.p3.p1.i64(ptr addrspace(3) align 16 [[DST]], ptr addrspace(1) align 16 [[SRC]], i64 16, i1 false)
; OPT-NEXT:    ret void
;
  call void @llvm.memmove.p3.p1.i64(ptr addrspace(3) align 16 %dst, ptr addrspace(1) align 16 %src, i64 16, i1 false)
  ret void
}

define amdgpu_kernel void @memset_lds_16(ptr addrspace(3) %dst, i8 %val) {
; OPT-LABEL: define amdgpu_kernel void @memset_lds_16(
; OPT-SAME: ptr addrspace(3) [[DST:%.*]], i8 [[VAL:%.*]]) {
; OPT-NEXT:    call void @llvm.memset.p3.i64(ptr addrspace(3) align 16 [[DST]], i8 [[VAL]], i64 16, i1 false)
; OPT-NEXT:    ret void
;
  call void @llvm.memset.p3.i64(ptr addrspace(3) align 16 %dst, i8 %val, i64 16, i1 false)
  ret void
}
