//===- LibraryOptions.h - Per-library TableGen options struct --*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Runtime support for the "one plain struct per library" options design
// generated by -gen-opt-parser-defs from OptionsStruct/Field/BoolField/
// ValueField/EnumField records (see llvm/include/llvm/Option/OptParser.td
// and llvm/utils/TableGen/OptionParserEmitter.cpp, OPTIONS_STRUCT_DECL /
// OPTIONS_STRUCT_DEFS). Each library declares exactly one such struct (e.g.
// llvm::PassesOptions), with a single process-wide instance (T::Current)
// registered here so that a shared driver (e.g. `opt`) can enumerate and
// apply command-line arguments to every registered library's struct without
// each tool needing per-library knowledge.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_OPTION_LIBRARYOPTIONS_H
#define LLVM_OPTION_LIBRARYOPTIONS_H

#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/raw_ostream.h"
#include <cstdint>
#include <optional>
#include <string>

namespace llvm {

// Forward-declared (rather than including TypeSize.h here) so this common
// header stays light; only VectorizeOptions.cpp needs the full definition.
class ElementCount;

namespace opt {

/// Converts the textual value of a Joined option's argument into a struct
/// field. Overloaded (not specialized) so ADL/overload resolution can find
/// the right conversion for whatever FieldType a ValueField<> option used;
/// generated apply() bodies simply call parseFieldValue(A.getValue(), Field).
LLVM_ABI bool parseFieldValue(StringRef Arg, std::string &Out);
LLVM_ABI bool parseFieldValue(StringRef Arg, bool &Out);
LLVM_ABI bool parseFieldValue(StringRef Arg, int &Out);
LLVM_ABI bool parseFieldValue(StringRef Arg, unsigned &Out);
LLVM_ABI bool parseFieldValue(StringRef Arg, uint64_t &Out);
LLVM_ABI bool parseFieldValue(StringRef Arg, int64_t &Out);
LLVM_ABI bool parseFieldValue(StringRef Arg, float &Out);
LLVM_ABI bool parseFieldValue(StringRef Arg, double &Out);
LLVM_ABI bool parseFieldValue(StringRef Arg, ElementCount &Out);

/// Supports OptionalValueField<>'s std::optional<T> fields: the Joined
/// (has-a-value) spelling parses into the wrapped type and wraps the
/// result; the paired bare spelling never calls this (it uses Assign<>
/// instead, see OptParser.td).
template <class T> bool parseFieldValue(StringRef Arg, std::optional<T> &Out) {
  T Val;
  if (!parseFieldValue(Arg, Val))
    return false;
  Out = std::move(Val);
  return true;
}

/// Registers a library's options struct so a shared multi-library command
/// line driver can enumerate and apply its options. `T` is a TableGen
/// -generated options struct (has static T::Current, static unsigned
/// T::Slot, static OptTable &T::table(), bool T::apply(const Arg&)).
LLVM_ABI unsigned allocateOptionsSlot();

template <class T> void registerLibraryOptions() {
  T::Slot = allocateOptionsSlot();
}

/// Static-initializer helper: declare
///   static llvm::opt::RegisterLibraryOptions<MyOptions> Registration;
/// once per library .cpp to register its options struct at load time.
template <class T> struct RegisterLibraryOptions {
  RegisterLibraryOptions() { registerLibraryOptions<T>(); }
};

/// Parses each Ts::Current in sequence, threading one struct's unrecognized
/// tokens into the next's input, so a tool linking several library options
/// structs (TableGen-generated or hand-written; both expose the same
/// `parse(Args, Rest, Errs)` signature) can compose them without hand-writing
/// the chain itself. Order matters only in that an earlier struct's Rest
/// output becomes a later struct's Args input.
template <class T1, class... Ts>
llvm::Error parseLibraryOptionsChain(llvm::ArrayRef<const char *> Args,
                                     llvm::SmallVectorImpl<const char *> &Rest,
                                     llvm::raw_ostream &Errs) {
  if constexpr (sizeof...(Ts) == 0) {
    return T1::Current.parse(Args, Rest, Errs);
  } else {
    llvm::SmallVector<const char *, 32> Intermediate;
    if (llvm::Error E = T1::Current.parse(Args, Intermediate, Errs))
      return E;
    return parseLibraryOptionsChain<Ts...>(Intermediate, Rest, Errs);
  }
}

} // namespace opt
} // namespace llvm

#endif // LLVM_OPTION_LIBRARYOPTIONS_H
