//===-- llvm-dwarfdump.cpp - Debug info dumping utility for llvm ----------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This program is a utility that works like "dwarfdump".
//
//===----------------------------------------------------------------------===//

#include "llvm-dwarfdump.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVectorExtras.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/DebugInfo/DIContext.h"
#include "llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h"
#include "llvm/DebugInfo/DWARF/DWARFCompileUnit.h"
#include "llvm/DebugInfo/DWARF/DWARFContext.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Object/Archive.h"
#include "llvm/Object/MachOUniversal.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/CommandLineV2.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Parallel.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Regex.h"
#include "llvm/Support/RegisterLLVMOptions.h"
#include "llvm/Support/TargetSelect.h"
#include "llvm/Support/Threading.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Support/WithColor.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TargetParser/Triple.h"
#include <cstdlib>

using namespace llvm;
using namespace llvm::clv2;
using namespace llvm::dwarfdump;
using namespace llvm::object;

// Sentinel types used by HANDLE_DWARF_SECTION to distinguish section kinds.
struct BoolOption {};   ///< Section flag that takes no offset.
struct OffsetOption {}; ///< Section flag that accepts an optional hex offset.

namespace {
enum ErrorDetailLevel {
  OnlyDetailsNoSummary,
  NoDetailsOnlySummary,
  NoDetailsOrSummary,
  BothDetailsAndSummary,
  Unspecified
};

static constexpr OptionCategory DwarfDumpCategory{"Specific Options"};
static constexpr OptionCategory SectionCategory{
    "Section-specific Dump Options",
    "These control which sections are dumped. "
    "Where applicable these parameters take an "
    "optional =<offset> argument to dump only "
    "the entry at the specified offset."};

static constexpr ListOptionInfo<std::string> InputFilenamesOpt{
    "input", "<input object files or .dSYM bundles>", Positional{},
    cat(DwarfDumpCategory)};

static constexpr OptionInfo<bool> DumpAllOpt{
    "all", "Dump all debug info sections", cat(SectionCategory)};
// -a is an alias for --all (handled via alias in help; no separate OptionInfo
// needed since clv2 short aliases are declared with the same flag letter)

// Section dump options generated by the x-macro: each section may take an
// optional =<offset> argument.  Represented as OptionInfo<std::string> with
// ValueOptional:  specified()+get()==""  → dump whole section;
//                 specified()+get()!=""  → dump entry at that offset.
// OffsetOption sections accept an optional =<offset> value.
// BoolOption sections are flags (ValueOptional for specified() but value
// placeholder suppressed; tool rejects values at runtime).
#define OffsetOption 1
#define BoolOption 0
#define DWARF_SECTION_MODS_1 value_desc("offset"), ValueOptional
#define DWARF_SECTION_MODS_0 suppress_val_placeholder, ValueOptional
#define DWARF_SECTION_MODS(OPTION) DWARF_SECTION_MODS_##OPTION
#define HANDLE_DWARF_SECTION(ENUM_NAME, ELF_NAME, CMDLINE_NAME, OPTION)        \
  static constexpr OptionInfo<std::string> Dump##ENUM_NAME##Opt{               \
      CMDLINE_NAME, "Dump the " ELF_NAME " section",                           \
      DWARF_SECTION_MODS(OPTION), cat(SectionCategory)};
#include "llvm/BinaryFormat/Dwarf.def"
#undef HANDLE_DWARF_SECTION
#undef DWARF_SECTION_MODS
#undef DWARF_SECTION_MODS_1
#undef DWARF_SECTION_MODS_0
#undef OffsetOption
#undef BoolOption

// --eh-frame is an alias for --debug-frame; no separate option needed.

static constexpr ListOptionInfo<std::string> ArchFiltersOpt{
    "arch",
    "Dump debug information for the specified CPU "
    "architecture only. Architectures may be specified by "
    "name or by number. This option can be specified "
    "multiple times, once for each desired architecture.",
    value_desc("string"), cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> DiffOpt{
    "diff", "Emit diff-friendly output by omitting offsets and addresses.",
    cat(DwarfDumpCategory)};
static constexpr ListOptionInfo<std::string> FindOpt{
    "find",
    "Search for the exact match for <name> in the accelerator tables "
    "and print the matching debug information entries. When no "
    "accelerator tables are available, the slower but more complete "
    "-name option can be used instead.",
    value_desc("name"), cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> FindAllAppleOpt{
    "find-all-apple",
    "Print every debug information entry in the accelerator tables.",
    cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> IgnoreCaseOpt{
    "ignore-case", "Ignore case distinctions when using --name.",
    cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> DumpNonSkeletonOpt{
    "dwo",
    "Dump the non skeleton DIE in the .dwo or .dwp file after dumping the "
    "skeleton DIE from the main executable. This allows dumping the .dwo "
    "files with resolved addresses.",
    cat(DwarfDumpCategory)};
static constexpr ListOptionInfo<std::string> NameOpt{
    "name",
    "Find and print all debug info entries whose name "
    "(DW_AT_name/DW_AT_linkage_name attribute) matches the exact text "
    "in <pattern>.  When used with the the -regex option <pattern> is "
    "interpreted as a regular expression.",
    value_desc("pattern"), cat(DwarfDumpCategory)};
static constexpr OptionInfo<uint64_t> LookupOpt{
    "lookup",
    "Lookup <address> in the debug information and print out any "
    "available file, function, block and line table details.",
    value_desc("address"), cat(DwarfDumpCategory)};
static constexpr OptionInfo<std::string> OutputFilenameOpt{
    "o", "Redirect output to the specified file.", value_desc("filename"),
    Init{"-"}, cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> UseRegexOpt{
    "regex",
    "Treat any <pattern> strings as regular "
    "expressions when searching with --name. If --ignore-case is also "
    "specified, the regular expression becomes case-insensitive.",
    cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> ShowChildrenOpt{
    "show-children",
    "Show a debug info entry's children when selectively printing entries.",
    cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> ShowParentsOpt{
    "show-parents",
    "Show a debug info entry's parents when selectively printing entries.",
    cat(DwarfDumpCategory)};
static constexpr ListOptionInfo<std::string> FilterChildTagOpt{
    "filter-child-tag",
    "When --show-children is specified, show only DIEs with the "
    "specified DWARF tags.",
    value_desc("list of DWARF tags"), cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> ShowFormOpt{
    "show-form", "Show DWARF form types after the DWARF attribute types.",
    cat(DwarfDumpCategory)};
static constexpr OptionInfo<unsigned> ChildRecurseDepthOpt{
    "recurse-depth",
    "Only recurse to a depth of N when displaying children of debug info "
    "entries.",
    value_desc("N"), Init{-1U}, cat(DwarfDumpCategory)};
static constexpr OptionInfo<unsigned> ParentRecurseDepthOpt{
    "parent-recurse-depth",
    "Only recurse to a depth of N when displaying parents of debug info "
    "entries.",
    value_desc("N"), Init{-1U}, cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> SummarizeTypesOpt{
    "summarize-types", "Abbreviate the description of type unit entries.",
    cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> StatisticsOpt{
    "statistics", "Emit JSON-formatted debug info quality metrics.",
    cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> ShowSectionSizesOpt{
    "show-section-sizes",
    "Show the sizes of all debug sections, expressed in bytes.",
    cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> ManuallyGenerateUnitIndexOpt{
    "manually-generate-unit-index",
    "if the input is dwp file, parse .debug_info "
    "section and use it to populate "
    "DW_SECT_INFO contributions in cu-index. "
    "For DWARF5 it also populated TU Index.",
    Init{false}, Hidden, cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> ShowSourcesOpt{
    "show-sources", "Show the sources across all compilation units.",
    cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> VerifyOpt{
    "verify", "Verify the DWARF debug info.", cat(DwarfDumpCategory)};
static constexpr OptionInfo<unsigned> VerifyNumThreadsOpt{
    "verify-num-threads",
    "Number of threads to use for --verify. Single threaded verification "
    "is the default unless this option is specified. If 0 is specified, "
    "maximum hardware threads will be used. This can cause the "
    "output to be non determinisitic, but can speed up verification and "
    "is useful when running with the summary only or JSON summary modes.",
    Init{1u}, cat(DwarfDumpCategory)};

static constexpr EnumVal<ErrorDetailLevel> ErrorDetailVals[] = {
    {"quiet", NoDetailsOrSummary, "Only display whether errors occurred."},
    {"summary", NoDetailsOnlySummary,
     "Display only a summary of the errors found."},
    {"details", OnlyDetailsNoSummary,
     "Display each error in detail but no summary."},
    {"full", BothDetailsAndSummary,
     "Display each error as well as a summary. [default]"},
};
static constexpr OptionInfo<ErrorDetailLevel> ErrorDetailsOpt{
    "error-display",
    "Set the level of detail and summary to display when verifying "
    "(implies --verify)",
    Init{Unspecified}, ValuesRef(ErrorDetailVals), cat(DwarfDumpCategory)};
static constexpr OptionInfo<std::string> JsonErrSummaryFileOpt{
    "verify-json",
    "Output JSON-formatted error summary to the specified file. "
    "(Implies --verify)",
    value_desc("filename.json"), cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> QuietOpt{
    "quiet", "Use with -verify to not emit to STDOUT.", cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> DumpUUIDOpt{
    "uuid", "Show the UUID for each architecture.", cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> VerboseOpt{
    "verbose", "Print more low-level encoding details.",
    cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> ShowVariableCoverageOpt{
    "show-variable-coverage", "Show per-variable coverage metrics.",
    cat(DwarfDumpCategory)};
static constexpr OptionInfo<std::string> CoverageBaselineOpt{
    "coverage-baseline",
    "File to use as the baseline for variable coverage "
    "statistics (implies --show-variable-coverage)",
    value_desc("filename"), cat(DwarfDumpCategory)};
static constexpr OptionInfo<std::string> BitcodeFileOpt{
    "variable-coverage-bitcode-file",
    "File containing LLVM IR (bitcode or textual) used for "
    "calculating variable definedness in coverage statistics "
    "(implies --show-variable-coverage)",
    value_desc("filename"), cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> CombineInstancesOpt{
    "combine-inline-variable-instances",
    "Use with --show-variable-coverage to average variable coverage across "
    "inlined subroutine instances instead of printing them separately.",
    cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> DumpUUIDShortOpt{"u", "Alias for --uuid.",
                                                   cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> VerboseShortOpt{"v", "Alias for --verbose.",
                                                  cat(DwarfDumpCategory)};
static constexpr ListOptionInfo<std::string> FindShortOpt{
    "f", "Alias for --find.", suppress_val_placeholder, cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> IgnoreCaseShortOpt{
    "i", "Alias for --ignore-case.", cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> UseRegexShortOpt{"x", "Alias for --regex",
                                                   cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> ShowChildrenShortOpt{
    "c", "Alias for --show-children.", cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> ShowParentsShortOpt{
    "p", "Alias for --show-parents.", cat(DwarfDumpCategory)};
static constexpr ListOptionInfo<std::string> FilterChildTagShortOpt{
    "t", "Alias for --filter-child-tag.", suppress_val_placeholder,
    cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> ShowFormShortOpt{
    "F", "Alias for --show-form.", cat(DwarfDumpCategory)};
static constexpr OptionInfo<unsigned> ChildRecurseDepthShortOpt{
    "r", "Alias for --recurse-depth.", suppress_val_placeholder, Init{-1U},
    cat(DwarfDumpCategory)};
static constexpr OptionInfo<bool> DumpAllShortOpt{"a", "Alias for --all",
                                                  cat(SectionCategory)};
static constexpr ListOptionInfo<std::string> NameShortOpt{
    "n", "Alias for --name", suppress_val_placeholder, cat(DwarfDumpCategory)};
static constexpr OptionInfo<std::string> OutputFilenameAliasOpt{
    "out-file", "Alias for -o.", Hidden, cat(DwarfDumpCategory)};
static constexpr OptionInfo<std::string> EhFrameOpt{
    "eh-frame", "Alias for --debug-frame", suppress_val_placeholder,
    ValueOptional, cat(SectionCategory)};

static constexpr OptionsRegistry<
    &InputFilenamesOpt, &DumpAllOpt, &DumpAllShortOpt,
#define HANDLE_DWARF_SECTION(ENUM_NAME, ELF_NAME, CMDLINE_NAME, OPTION)        \
  &Dump##ENUM_NAME##Opt,
#include "llvm/BinaryFormat/Dwarf.def"
#undef HANDLE_DWARF_SECTION
    &EhFrameOpt, &ArchFiltersOpt, &DiffOpt, &FindOpt, &FindShortOpt,
    &FindAllAppleOpt, &IgnoreCaseOpt, &IgnoreCaseShortOpt, &DumpNonSkeletonOpt,
    &NameOpt, &NameShortOpt, &LookupOpt, &OutputFilenameOpt,
    &OutputFilenameAliasOpt, &UseRegexOpt, &UseRegexShortOpt, &ShowChildrenOpt,
    &ShowChildrenShortOpt, &ShowParentsOpt, &ShowParentsShortOpt,
    &FilterChildTagOpt, &FilterChildTagShortOpt, &ShowFormOpt,
    &ShowFormShortOpt, &ChildRecurseDepthOpt, &ChildRecurseDepthShortOpt,
    &ParentRecurseDepthOpt, &SummarizeTypesOpt, &StatisticsOpt,
    &ShowSectionSizesOpt, &ManuallyGenerateUnitIndexOpt, &ShowSourcesOpt,
    &VerifyOpt, &VerifyNumThreadsOpt, &ErrorDetailsOpt, &JsonErrSummaryFileOpt,
    &QuietOpt, &DumpUUIDOpt, &DumpUUIDShortOpt, &VerboseOpt, &VerboseShortOpt,
    &ShowVariableCoverageOpt, &CoverageBaselineOpt, &BitcodeFileOpt,
    &CombineInstancesOpt>
    DwarfDumpToolReg;
} // namespace

/// Parsed command-line values, threaded through helper functions.
struct DwarfDumpArgs {
  std::vector<std::string> InputFilenames;
  bool DumpAll;
  std::vector<std::string> ArchFilters;
  bool Diff;
  std::vector<std::string> Find;
  bool FindAllApple;
  bool IgnoreCase;
  bool DumpNonSkeleton;
  std::vector<std::string> Name;
  uint64_t Lookup;
  bool HasLookup;
  std::string OutputFilename;
  bool UseRegex;
  bool ShowChildren;
  bool ShowParents;
  std::vector<std::string> FilterChildTag;
  bool ShowForm;
  unsigned ChildRecurseDepth;
  unsigned ParentRecurseDepth;
  bool SummarizeTypes;
  bool Statistics;
  bool ShowSectionSizes;
  bool ManuallyGenerateUnitIndex;
  bool ShowSources;
  bool Verify;
  unsigned VerifyNumThreads;
  ErrorDetailLevel ErrorDetails;
  std::string JsonErrSummaryFile;
  bool Quiet;
  bool DumpUUID;
  bool Verbose;
  bool ShowVariableCoverage;
  std::string CoverageBaseline;
  std::string BitcodeFile;
  bool CombineInstances;
  unsigned DumpType;
  std::array<std::optional<uint64_t>, (unsigned)DIDT_ID_Count> DumpOffsets;
};

//===----------------------------------------------------------------------===//

static llvm::SmallVector<unsigned>
makeTagVector(const std::vector<std::string> &TagStrings) {
  return llvm::map_to_vector(TagStrings, [](const std::string &Tag) {
    return llvm::dwarf::getTag(Tag);
  });
}

static void error(Error Err) {
  if (!Err)
    return;
  WithColor::error() << toString(std::move(Err)) << "\n";
  exit(1);
}

static void error(StringRef Prefix, Error Err) {
  if (!Err)
    return;
  WithColor::error() << Prefix << ": " << toString(std::move(Err)) << "\n";
  exit(1);
}

static void error(StringRef Prefix, std::error_code EC) {
  error(Prefix, errorCodeToError(EC));
}

static DIDumpOptions getDumpOpts(DWARFContext &C, const DwarfDumpArgs &Args) {
  DIDumpOptions DumpOpts;
  DumpOpts.DumpType = Args.DumpType;
  DumpOpts.ChildRecurseDepth = Args.ChildRecurseDepth;
  DumpOpts.ParentRecurseDepth = Args.ParentRecurseDepth;
  DumpOpts.ShowAddresses = !Args.Diff;
  DumpOpts.ShowChildren = Args.ShowChildren;
  DumpOpts.ShowParents = Args.ShowParents;
  DumpOpts.FilterChildTag = makeTagVector(Args.FilterChildTag);
  DumpOpts.ShowForm = Args.ShowForm;
  DumpOpts.SummarizeTypes = Args.SummarizeTypes;
  DumpOpts.Verbose = Args.Verbose;
  DumpOpts.DumpNonSkeleton = Args.DumpNonSkeleton;
  DumpOpts.RecoverableErrorHandler = C.getRecoverableErrorHandler();
  // In -verify mode, print DIEs without children in error messages.
  if (Args.Verify) {
    DumpOpts.Verbose = Args.ErrorDetails != NoDetailsOnlySummary &&
                       Args.ErrorDetails != NoDetailsOrSummary;
    DumpOpts.ShowAggregateErrors = Args.ErrorDetails != OnlyDetailsNoSummary &&
                                   Args.ErrorDetails != NoDetailsOnlySummary;
    DumpOpts.JsonErrSummaryFile = Args.JsonErrSummaryFile;
    return DumpOpts.noImplicitRecursion();
  }
  return DumpOpts;
}

static uint32_t getCPUType(MachOObjectFile &MachO) {
  if (MachO.is64Bit())
    return MachO.getHeader64().cputype;
  else
    return MachO.getHeader().cputype;
}

/// Return true if the object file has not been filtered by an --arch option.
static bool filterArch(ObjectFile &Obj,
                       const std::vector<std::string> &ArchFilters) {
  if (ArchFilters.empty())
    return true;

  if (auto *MachO = dyn_cast<MachOObjectFile>(&Obj)) {
    for (const StringRef Arch : ArchFilters) {
      // Match architecture number.
      unsigned Value;
      if (!Arch.getAsInteger(0, Value))
        if (Value == getCPUType(*MachO))
          return true;

      // Match as name.
      if (MachO->getArchTriple().getArchName() == Triple(Arch).getArchName())
        return true;
    }
  }
  return false;
}

using HandlerFn = std::function<bool(ObjectFile &, DWARFContext &DICtx,
                                     const Twine &, raw_ostream &)>;

/// Print only DIEs that have a certain name.
static bool filterByName(
    const StringSet<> &Names, DWARFDie Die, StringRef NameRef, raw_ostream &OS,
    std::function<StringRef(uint64_t RegNum, bool IsEH)> GetNameForDWARFReg,
    const DwarfDumpArgs &Args) {
  DIDumpOptions DumpOpts = getDumpOpts(Die.getDwarfUnit()->getContext(), Args);
  DumpOpts.GetNameForDWARFReg = GetNameForDWARFReg;
  std::string Name =
      (Args.IgnoreCase && !Args.UseRegex) ? NameRef.lower() : NameRef.str();
  if (Args.UseRegex) {
    // Match regular expression.
    for (auto Pattern : Names.keys()) {
      Regex RE(Pattern, Args.IgnoreCase ? Regex::IgnoreCase : Regex::NoFlags);
      std::string Error;
      if (!RE.isValid(Error)) {
        errs() << "error in regular expression: " << Error << "\n";
        exit(1);
      }
      if (RE.match(Name)) {
        Die.dump(OS, 0, DumpOpts);
        return true;
      }
    }
  } else if (Names.count(Name)) {
    // Match full text.
    Die.dump(OS, 0, DumpOpts);
    return true;
  }
  return false;
}

/// Print only DIEs that have a certain name.
static void filterByName(
    const StringSet<> &Names, DWARFContext::unit_iterator_range CUs,
    raw_ostream &OS,
    std::function<StringRef(uint64_t RegNum, bool IsEH)> GetNameForDWARFReg,
    const DwarfDumpArgs &Args) {
  auto filterDieNames = [&](DWARFUnit *Unit) {
    for (const auto &Entry : Unit->dies()) {
      DWARFDie Die = {Unit, &Entry};
      if (const char *Name = Die.getName(DINameKind::ShortName))
        if (filterByName(Names, Die, Name, OS, GetNameForDWARFReg, Args))
          continue;
      if (const char *Name = Die.getName(DINameKind::LinkageName))
        filterByName(Names, Die, Name, OS, GetNameForDWARFReg, Args);
    }
  };
  for (const auto &CU : CUs) {
    filterDieNames(CU.get());
    if (Args.DumpNonSkeleton) {
      // If we have split DWARF, then recurse down into the .dwo files as well.
      // Matching DIEs are printed as they are found and nothing here outlives
      // them, so the split unit can be released instead of keeping every .dwo
      // context resident until the end of the search.
      const bool HadDWO = CU->getDWO();
      DWARFDie CUDie = CU->getUnitDIE(false);
      DWARFDie CUNonSkeletonDie = CU->getNonSkeletonUnitDIE(false);
      // If we have a DWO file, we need to search it as well
      if (CUNonSkeletonDie && CUDie != CUNonSkeletonDie)
        filterDieNames(CUNonSkeletonDie.getDwarfUnit());
      const DWARFUnit *DWO = CU->getDWO();
      // Don't release a DWP context -- it is the same for every non-skeleton CU
      // and we benefit from keeping it resident to avoid the re-parse.
      if (!HadDWO && DWO && !DWO->getContext().isDWP())
        CU->clearDWO();
    }
  }
}

static void getDies(DWARFContext &DICtx, const AppleAcceleratorTable &Accel,
                    StringRef Name, SmallVectorImpl<DWARFDie> &Dies) {
  for (const auto &Entry : Accel.equal_range(Name)) {
    if (std::optional<uint64_t> Off = Entry.getDIESectionOffset()) {
      if (DWARFDie Die = DICtx.getDIEForOffset(*Off))
        Dies.push_back(Die);
    }
  }
}

static DWARFDie toDie(const DWARFDebugNames::Entry &Entry,
                      DWARFContext &DICtx) {
  std::optional<uint64_t> CUOff = Entry.getCUOffset();
  std::optional<uint64_t> Off = Entry.getDIEUnitOffset();
  if (!CUOff || !Off)
    return DWARFDie();

  DWARFCompileUnit *CU = DICtx.getCompileUnitForOffset(*CUOff);
  if (!CU)
    return DWARFDie();

  if (std::optional<uint64_t> DWOId = CU->getDWOId()) {
    // This is a skeleton unit. Look up the DIE in the DWO unit.
    CU = DICtx.getDWOCompileUnitForHash(*DWOId);
    if (!CU)
      return DWARFDie();
  }

  return CU->getDIEForOffset(CU->getOffset() + *Off);
}

static void getDies(DWARFContext &DICtx, const DWARFDebugNames &Accel,
                    StringRef Name, SmallVectorImpl<DWARFDie> &Dies) {
  for (const auto &Entry : Accel.equal_range(Name)) {
    if (DWARFDie Die = toDie(Entry, DICtx))
      Dies.push_back(Die);
  }
}

/// Print only DIEs that have a certain name.
static void filterByAccelName(
    ArrayRef<std::string> Names, DWARFContext &DICtx, raw_ostream &OS,
    std::function<StringRef(uint64_t RegNum, bool IsEH)> GetNameForDWARFReg,
    const DwarfDumpArgs &Args) {
  SmallVector<DWARFDie, 4> Dies;
  for (const auto &Name : Names) {
    getDies(DICtx, DICtx.getAppleNames(), Name, Dies);
    getDies(DICtx, DICtx.getAppleTypes(), Name, Dies);
    getDies(DICtx, DICtx.getAppleNamespaces(), Name, Dies);
    getDies(DICtx, DICtx.getDebugNames(), Name, Dies);
  }
  llvm::sort(Dies);
  Dies.erase(llvm::unique(Dies), Dies.end());

  DIDumpOptions DumpOpts = getDumpOpts(DICtx, Args);
  DumpOpts.GetNameForDWARFReg = GetNameForDWARFReg;
  for (DWARFDie Die : Dies)
    Die.dump(OS, 0, DumpOpts);
}

/// Print all DIEs in apple accelerator tables
static void findAllApple(
    DWARFContext &DICtx, raw_ostream &OS,
    std::function<StringRef(uint64_t RegNum, bool IsEH)> GetNameForDWARFReg,
    const DwarfDumpArgs &Args) {
  MapVector<StringRef, llvm::SmallSet<DWARFDie, 2>> NameToDies;

  auto PushDIEs = [&](const AppleAcceleratorTable &Accel) {
    for (const auto &Entry : Accel.entries()) {
      if (std::optional<uint64_t> Off = Entry.BaseEntry.getDIESectionOffset()) {
        std::optional<StringRef> MaybeName = Entry.readName();
        DWARFDie Die = DICtx.getDIEForOffset(*Off);
        if (Die && MaybeName)
          NameToDies[*MaybeName].insert(Die);
      }
    }
  };

  PushDIEs(DICtx.getAppleNames());
  PushDIEs(DICtx.getAppleNamespaces());
  PushDIEs(DICtx.getAppleTypes());

  DIDumpOptions DumpOpts = getDumpOpts(DICtx, Args);
  DumpOpts.GetNameForDWARFReg = GetNameForDWARFReg;
  for (const auto &[Name, Dies] : NameToDies) {
    OS << llvm::formatv("\nApple accelerator entries with name = \"{0}\":\n",
                        Name);
    for (DWARFDie Die : Dies)
      Die.dump(OS, 0, DumpOpts);
  }
}

/// Handle the --lookup option and dump the DIEs and line info for the given
/// address.
/// TODO: specified Address for --lookup option could relate for several
/// different sections(in case not-linked object file). llvm-dwarfdump
/// need to do something with this: extend lookup option with section
/// information or probably display all matched entries, or something else...
static bool lookup(ObjectFile &Obj, DWARFContext &DICtx, uint64_t Address,
                   raw_ostream &OS, const DwarfDumpArgs &Args) {
  auto DIEsForAddr = DICtx.getDIEsForAddress(Address, Args.DumpNonSkeleton);

  if (!DIEsForAddr)
    return false;

  DIDumpOptions DumpOpts = getDumpOpts(DICtx, Args);
  DumpOpts.ChildRecurseDepth = 0;
  DIEsForAddr.CompileUnit->dump(OS, DumpOpts);
  if (DIEsForAddr.FunctionDIE) {
    DIEsForAddr.FunctionDIE.dump(OS, 2, DumpOpts);
    if (DIEsForAddr.BlockDIE)
      DIEsForAddr.BlockDIE.dump(OS, 4, DumpOpts);
  }

  // TODO: it is neccessary to set proper SectionIndex here.
  // object::SectionedAddress::UndefSection works for only absolute addresses.
  if (DILineInfo LineInfo =
          DICtx
              .getLineInfoForAddress(
                  {Address, object::SectionedAddress::UndefSection})
              .value_or(DILineInfo())) {
    LineInfo.dump(OS);
  }

  return true;
}

// Collect all sources referenced from the given line table, scoped to the given
// CU compilation directory.
static bool collectLineTableSources(const DWARFDebugLine::LineTable &LT,
                                    StringRef CompDir,
                                    std::vector<std::string> &Sources) {
  bool Result = true;
  std::optional<uint64_t> LastIndex = LT.getLastValidFileIndex();
  for (uint64_t I = LT.hasFileAtIndex(0) ? 0 : 1,
                E = LastIndex ? *LastIndex + 1 : 0;
       I < E; ++I) {
    std::string Path;
    Result &= LT.getFileNameByIndex(
        I, CompDir, DILineInfoSpecifier::FileLineInfoKind::AbsoluteFilePath,
        Path);
    Sources.push_back(std::move(Path));
  }
  return Result;
}

static bool collectObjectSources(ObjectFile &Obj, DWARFContext &DICtx,
                                 const Twine &Filename, raw_ostream &OS) {
  bool Result = true;
  std::vector<std::string> Sources;

  bool HasCompileUnits = false;
  for (const auto &CU : DICtx.compile_units()) {
    HasCompileUnits = true;
    // Extract paths from the line table for this CU. This allows combining the
    // compilation directory with the line information, in case both the include
    // directory and file names in the line table are relative.
    const DWARFDebugLine::LineTable *LT = DICtx.getLineTableForUnit(CU.get());
    StringRef CompDir = CU->getCompilationDir();
    if (LT) {
      Result &= collectLineTableSources(*LT, CompDir, Sources);
    } else {
      // Since there's no line table for this CU, collect the name from the CU
      // itself.
      const char *Name = CU->getUnitDIE().getShortName();
      if (!Name) {
        WithColor::warning()
            << Filename << ": missing name for compilation unit\n";
        continue;
      }
      SmallString<64> AbsName;
      if (sys::path::is_relative(Name, sys::path::Style::posix) &&
          sys::path::is_relative(Name, sys::path::Style::windows))
        AbsName = CompDir;
      sys::path::append(AbsName, Name);
      Sources.push_back(std::string(AbsName));
    }
  }

  if (!HasCompileUnits) {
    // Since there's no compile units available, walk the line tables and
    // extract out any referenced paths.
    DWARFDataExtractor LineData(DICtx.getDWARFObj(),
                                DICtx.getDWARFObj().getLineSection(),
                                DICtx.isLittleEndian(), 0);
    DWARFDebugLine::SectionParser Parser(LineData, DICtx, DICtx.normal_units());
    while (!Parser.done()) {
      const auto RecoverableErrorHandler = [&](Error Err) {
        Result = false;
        WithColor::defaultErrorHandler(std::move(Err));
      };
      void (*UnrecoverableErrorHandler)(Error Err) = error;

      DWARFDebugLine::LineTable LT =
          Parser.parseNext(RecoverableErrorHandler, UnrecoverableErrorHandler);
      Result &= collectLineTableSources(LT, /*CompDir=*/"", Sources);
    }
  }

  // Dedup and order the sources.
  llvm::sort(Sources);
  Sources.erase(llvm::unique(Sources), Sources.end());

  for (StringRef Name : Sources)
    OS << Name << "\n";
  return Result;
}

static std::unique_ptr<MCRegisterInfo>
createRegInfo(const object::ObjectFile &Obj) {
  std::unique_ptr<MCRegisterInfo> MCRegInfo;
  Triple TT;
  TT.setArch(Triple::ArchType(Obj.getArch()));
  TT.setVendor(Triple::UnknownVendor);
  TT.setOS(Triple::UnknownOS);
  std::string TargetLookupError;
  const Target *TheTarget = TargetRegistry::lookupTarget(TT, TargetLookupError);
  if (!TargetLookupError.empty())
    return nullptr;
  MCRegInfo.reset(TheTarget->createMCRegInfo(TT));
  return MCRegInfo;
}

static bool dumpObjectFile(ObjectFile &Obj, DWARFContext &DICtx,
                           const Twine &Filename, raw_ostream &OS,
                           const DwarfDumpArgs &Args) {

  auto MCRegInfo = createRegInfo(Obj);
  if (!MCRegInfo)
    logAllUnhandledErrors(createStringError(inconvertibleErrorCode(),
                                            "Error in creating MCRegInfo"),
                          errs(), Filename + ": ");

  auto GetRegName = [&MCRegInfo](uint64_t DwarfRegNum, bool IsEH) -> StringRef {
    if (!MCRegInfo)
      return {};
    if (std::optional<MCRegister> LLVMRegNum =
            MCRegInfo->getLLVMRegNum(DwarfRegNum, IsEH))
      if (const char *RegName = MCRegInfo->getName(*LLVMRegNum))
        return StringRef(RegName);
    return {};
  };

  // The UUID dump already contains all the same information.
  if (!(Args.DumpType & DIDT_UUID) || Args.DumpType == DIDT_All)
    OS << Filename << ":\tfile format " << Obj.getFileFormatName() << '\n';

  // Handle the --lookup option.
  if (Args.HasLookup)
    return lookup(Obj, DICtx, Args.Lookup, OS, Args);

  // Handle the --name option.
  if (!Args.Name.empty()) {
    StringSet<> Names;
    for (const auto &name : Args.Name)
      Names.insert((Args.IgnoreCase && !Args.UseRegex) ? StringRef(name).lower()
                                                       : name);

    filterByName(Names, DICtx.normal_units(), OS, GetRegName, Args);
    filterByName(Names, DICtx.dwo_units(), OS, GetRegName, Args);
    return true;
  }

  // Handle the --find option and lower it to --debug-info=<offset>.
  if (!Args.Find.empty()) {
    filterByAccelName(Args.Find, DICtx, OS, GetRegName, Args);
    return true;
  }

  // Handle the --find-all-apple option and lower it to --debug-info=<offset>.
  if (Args.FindAllApple) {
    findAllApple(DICtx, OS, GetRegName, Args);
    return true;
  }

  // Dump the complete DWARF structure.
  auto DumpOpts = getDumpOpts(DICtx, Args);
  DumpOpts.GetNameForDWARFReg = GetRegName;
  DICtx.dump(OS, DumpOpts, Args.DumpOffsets);
  return true;
}

static bool verifyObjectFile(ObjectFile &Obj, DWARFContext &DICtx,
                             const Twine &Filename, raw_ostream &OS,
                             const DwarfDumpArgs &Args) {
  // Verify the DWARF and exit with non-zero exit status if verification
  // fails.
  raw_ostream &stream = Args.Quiet ? nulls() : OS;
  stream << "Verifying " << Filename.str() << ":\tfile format "
         << Obj.getFileFormatName() << "\n";
  bool Result = DICtx.verify(stream, getDumpOpts(DICtx, Args));
  if (Result)
    stream << "No errors.\n";
  else
    stream << "Errors detected.\n";
  return Result;
}

static bool handleBuffer(StringRef Filename, MemoryBufferRef Buffer,
                         HandlerFn HandleObj, raw_ostream &OS,
                         const std::vector<std::string> &ArchFilters,
                         bool ManuallyGenerateUnitIndex);

static bool handleArchive(StringRef Filename, Archive &Arch,
                          HandlerFn HandleObj, raw_ostream &OS,
                          const std::vector<std::string> &ArchFilters,
                          bool ManuallyGenerateUnitIndex) {
  bool Result = true;
  Error Err = Error::success();
  for (const auto &Child : Arch.children(Err)) {
    auto BuffOrErr = Child.getMemoryBufferRef();
    error(Filename, BuffOrErr.takeError());
    auto NameOrErr = Child.getName();
    error(Filename, NameOrErr.takeError());
    std::string Name = (Filename + "(" + NameOrErr.get() + ")").str();
    Result &= handleBuffer(Name, BuffOrErr.get(), HandleObj, OS, ArchFilters,
                           ManuallyGenerateUnitIndex);
  }
  error(Filename, std::move(Err));

  return Result;
}

static bool handleBuffer(StringRef Filename, MemoryBufferRef Buffer,
                         HandlerFn HandleObj, raw_ostream &OS,
                         const std::vector<std::string> &ArchFilters,
                         bool ManuallyGenerateUnitIndex) {
  Expected<std::unique_ptr<Binary>> BinOrErr = object::createBinary(Buffer);
  error(Filename, BinOrErr.takeError());

  bool Result = true;
  auto RecoverableErrorHandler = [&](Error E) {
    Result = false;
    WithColor::defaultErrorHandler(std::move(E));
  };
  if (auto *Obj = dyn_cast<ObjectFile>(BinOrErr->get())) {
    if (filterArch(*Obj, ArchFilters)) {
      std::unique_ptr<DWARFContext> DICtx = DWARFContext::create(
          *Obj, DWARFContext::ProcessDebugRelocations::Process, nullptr, "",
          RecoverableErrorHandler, WithColor::defaultWarningHandler,
          /*ThreadSafe=*/true);
      DICtx->setParseCUTUIndexManually(ManuallyGenerateUnitIndex);
      if (!HandleObj(*Obj, *DICtx, Filename, OS))
        Result = false;
    }
  } else if (auto *Fat = dyn_cast<MachOUniversalBinary>(BinOrErr->get()))
    for (auto &ObjForArch : Fat->objects()) {
      std::string ObjName =
          (Filename + "(" + ObjForArch.getArchFlagName() + ")").str();
      if (auto MachOOrErr = ObjForArch.getAsObjectFile()) {
        auto &Obj = **MachOOrErr;
        if (filterArch(Obj, ArchFilters)) {
          std::unique_ptr<DWARFContext> DICtx = DWARFContext::create(
              Obj, DWARFContext::ProcessDebugRelocations::Process, nullptr, "",
              RecoverableErrorHandler);
          DICtx->setParseCUTUIndexManually(ManuallyGenerateUnitIndex);
          if (!HandleObj(Obj, *DICtx, ObjName, OS))
            Result = false;
        }
        continue;
      } else
        consumeError(MachOOrErr.takeError());
      if (auto ArchiveOrErr = ObjForArch.getAsArchive()) {
        error(ObjName, ArchiveOrErr.takeError());
        if (!handleArchive(ObjName, *ArchiveOrErr.get(), HandleObj, OS,
                           ArchFilters, ManuallyGenerateUnitIndex))
          Result = false;
        continue;
      } else
        consumeError(ArchiveOrErr.takeError());
    }
  else if (auto *Arch = dyn_cast<Archive>(BinOrErr->get()))
    Result = handleArchive(Filename, *Arch, HandleObj, OS, ArchFilters,
                           ManuallyGenerateUnitIndex);
  return Result;
}

static bool handleFile(StringRef Filename, HandlerFn HandleObj, raw_ostream &OS,
                       const std::vector<std::string> &ArchFilters,
                       bool ManuallyGenerateUnitIndex) {
  ErrorOr<std::unique_ptr<MemoryBuffer>> BuffOrErr =
      MemoryBuffer::getFileOrSTDIN(Filename);
  error(Filename, BuffOrErr.getError());
  std::unique_ptr<MemoryBuffer> Buffer = std::move(BuffOrErr.get());
  return handleBuffer(Filename, *Buffer, HandleObj, OS, ArchFilters,
                      ManuallyGenerateUnitIndex);
}

int main(int argc, char **argv) {
  InitLLVM X(argc, argv);

  // Flush outs() when printing to errs(). This avoids interleaving output
  // between the two.
  errs().tie(&outs());

  llvm::InitializeAllTargetInfos();
  llvm::InitializeAllTargetMCs();

  clv2::OptionParser P;
  P.add<&DwarfDumpToolReg>();
  RegisterAllLLVMOptions(P);
  P.hideUnrelatedOptions(
      {&DwarfDumpCategory, &SectionCategory, &getColorCategory()});
  P.setExtraHelp("\nPass @FILE as argument to read options from FILE.\n");
  auto OptsCtx = P.parse(argc, argv,
                         "pretty-print DWARF debug information in object files"
                         " and debug info archives.\n");
  auto *ParsedOpts = OptsCtx->getViewPtr<&DwarfDumpToolReg>();

  DwarfDumpArgs Args;
  Args.InputFilenames = ParsedOpts->get<&InputFilenamesOpt>();
  Args.DumpAll =
      ParsedOpts->get<&DumpAllOpt>() || ParsedOpts->get<&DumpAllShortOpt>();
  Args.ArchFilters = ParsedOpts->get<&ArchFiltersOpt>();
  Args.Diff = ParsedOpts->get<&DiffOpt>();
  Args.Find = ParsedOpts->get<&FindOpt>();
  {
    auto ShortFind = ParsedOpts->get<&FindShortOpt>();
    Args.Find.insert(Args.Find.end(), ShortFind.begin(), ShortFind.end());
  }
  Args.FindAllApple = ParsedOpts->get<&FindAllAppleOpt>();
  Args.IgnoreCase = ParsedOpts->get<&IgnoreCaseOpt>() ||
                    ParsedOpts->get<&IgnoreCaseShortOpt>();
  Args.DumpNonSkeleton = ParsedOpts->get<&DumpNonSkeletonOpt>();
  Args.Name = ParsedOpts->get<&NameOpt>();
  {
    auto ShortName = ParsedOpts->get<&NameShortOpt>();
    Args.Name.insert(Args.Name.end(), ShortName.begin(), ShortName.end());
  }
  Args.HasLookup = ParsedOpts->specified<&LookupOpt>();
  Args.Lookup = ParsedOpts->get<&LookupOpt>();
  Args.OutputFilename = ParsedOpts->get<&OutputFilenameOpt>();
  if (ParsedOpts->specified<&OutputFilenameAliasOpt>())
    Args.OutputFilename = ParsedOpts->get<&OutputFilenameAliasOpt>();
  Args.UseRegex =
      ParsedOpts->get<&UseRegexOpt>() || ParsedOpts->get<&UseRegexShortOpt>();
  Args.ShowChildren = ParsedOpts->get<&ShowChildrenOpt>() ||
                      ParsedOpts->get<&ShowChildrenShortOpt>();
  Args.ShowParents = ParsedOpts->get<&ShowParentsOpt>() ||
                     ParsedOpts->get<&ShowParentsShortOpt>();
  Args.FilterChildTag = ParsedOpts->get<&FilterChildTagOpt>();
  {
    auto ShortTag = ParsedOpts->get<&FilterChildTagShortOpt>();
    Args.FilterChildTag.insert(Args.FilterChildTag.end(), ShortTag.begin(),
                               ShortTag.end());
  }
  Args.ShowForm =
      ParsedOpts->get<&ShowFormOpt>() || ParsedOpts->get<&ShowFormShortOpt>();
  Args.ChildRecurseDepth = ParsedOpts->get<&ChildRecurseDepthOpt>();
  // -r alias overrides --recurse-depth only if it was actually specified
  if (ParsedOpts->specified<&ChildRecurseDepthShortOpt>())
    Args.ChildRecurseDepth = ParsedOpts->get<&ChildRecurseDepthShortOpt>();
  Args.ParentRecurseDepth = ParsedOpts->get<&ParentRecurseDepthOpt>();
  Args.SummarizeTypes = ParsedOpts->get<&SummarizeTypesOpt>();
  Args.Statistics = ParsedOpts->get<&StatisticsOpt>();
  Args.ShowSectionSizes = ParsedOpts->get<&ShowSectionSizesOpt>();
  Args.ManuallyGenerateUnitIndex =
      ParsedOpts->get<&ManuallyGenerateUnitIndexOpt>();
  Args.ShowSources = ParsedOpts->get<&ShowSourcesOpt>();
  Args.Verify = ParsedOpts->get<&VerifyOpt>();
  Args.VerifyNumThreads = ParsedOpts->get<&VerifyNumThreadsOpt>();
  Args.ErrorDetails = ParsedOpts->get<&ErrorDetailsOpt>();
  Args.JsonErrSummaryFile = ParsedOpts->get<&JsonErrSummaryFileOpt>();
  Args.Quiet = ParsedOpts->get<&QuietOpt>();
  Args.DumpUUID =
      ParsedOpts->get<&DumpUUIDOpt>() || ParsedOpts->get<&DumpUUIDShortOpt>();
  Args.Verbose =
      ParsedOpts->get<&VerboseOpt>() || ParsedOpts->get<&VerboseShortOpt>();
  Args.ShowVariableCoverage = ParsedOpts->get<&ShowVariableCoverageOpt>();
  Args.CoverageBaseline = ParsedOpts->get<&CoverageBaselineOpt>();
  Args.BitcodeFile = ParsedOpts->get<&BitcodeFileOpt>();
  Args.CombineInstances = ParsedOpts->get<&CombineInstancesOpt>();

  // FIXME: Audit interactions between these two options and make them
  //        compatible.
  if (Args.Diff && Args.Verbose) {
    WithColor::error() << "incompatible arguments: specifying both -diff and "
                          "-verbose is currently not supported";
    return 1;
  }
  // -error-detail and -json-summary-file both imply -verify
  if (Args.ErrorDetails != Unspecified || !Args.JsonErrSummaryFile.empty()) {
    Args.Verify = true;
  }

  std::error_code EC;
  ToolOutputFile OutputFile(Args.OutputFilename, EC, sys::fs::OF_TextWithCRLF);
  error("unable to open output file " + Args.OutputFilename, EC);
  // Don't remove output file if we exit with an error.
  OutputFile.keep();

  // Build DumpType bitmask and DumpOffsets from the section options.
  Args.DumpType = DIDT_Null;
  Args.DumpOffsets = {};
  bool OffsetRequested = false;

#define HANDLE_DWARF_SECTION(ENUM_NAME, ELF_NAME, CMDLINE_NAME, OPTION)        \
  if (ParsedOpts->specified<&Dump##ENUM_NAME##Opt>()) {                        \
    Args.DumpType |= DIDT_##ENUM_NAME;                                         \
    StringRef SectionVal = ParsedOpts->get<&Dump##ENUM_NAME##Opt>();           \
    if (!SectionVal.empty()) {                                                 \
      constexpr bool IsBool = std::is_same_v<OPTION, BoolOption>;              \
      if (IsBool) {                                                            \
        WithColor::error()                                                     \
            << "for the --" CMDLINE_NAME                                       \
            << " option: this is a flag and does not take a value\n";          \
        return 1;                                                              \
      }                                                                        \
      uint64_t Offset;                                                         \
      if (SectionVal.getAsInteger(0, Offset)) {                                \
        WithColor::error() << "'" << SectionVal                                \
                           << "' is not a valid offset for --" CMDLINE_NAME    \
                           << "\n";                                            \
        return 1;                                                              \
      }                                                                        \
      Args.DumpOffsets[DIDT_ID_##ENUM_NAME] = Offset;                          \
      OffsetRequested = true;                                                  \
    }                                                                          \
  }
#include "llvm/BinaryFormat/Dwarf.def"
#undef HANDLE_DWARF_SECTION

  // --eh-frame is an alias for --debug-frame
  if (ParsedOpts->specified<&EhFrameOpt>()) {
    Args.DumpType |= DIDT_DebugFrame;
    StringRef SectionVal = ParsedOpts->get<&EhFrameOpt>();
    if (!SectionVal.empty()) {
      uint64_t Offset;
      if (SectionVal.getAsInteger(0, Offset)) {
        WithColor::error() << "'" << SectionVal
                           << "' is not a valid offset for --eh-frame\n";
        return 1;
      }
      Args.DumpOffsets[DIDT_ID_DebugFrame] = Offset;
      OffsetRequested = true;
    }
  }

  if (Args.DumpUUID)
    Args.DumpType |= DIDT_UUID;
  if (Args.DumpAll)
    Args.DumpType = DIDT_All;
  if (Args.DumpType == DIDT_Null && !Args.ShowVariableCoverage &&
      Args.CoverageBaseline.empty() && Args.BitcodeFile.empty()) {
    if (Args.Verbose || Args.Verify)
      Args.DumpType = DIDT_All;
    else
      Args.DumpType = DIDT_DebugInfo;
  }

  // Unless dumping a specific DIE, default to --show-children.
  if (!Args.ShowChildren && !Args.Verify && !OffsetRequested &&
      Args.Name.empty() && Args.Find.empty() && !Args.FindAllApple)
    Args.ShowChildren = true;

  // Defaults to a.out if no filenames specified.
  if (Args.InputFilenames.empty())
    Args.InputFilenames.push_back("a.out");

  // Expand any .dSYM bundles to the individual object files contained therein.
  std::vector<std::string> Objects;
  for (const auto &F : Args.InputFilenames) {
    if (auto DsymObjectsOrErr = MachOObjectFile::findDsymObjectMembers(F)) {
      if (DsymObjectsOrErr->empty())
        Objects.push_back(F);
      else
        llvm::append_range(Objects, *DsymObjectsOrErr);
    } else {
      error(DsymObjectsOrErr.takeError());
    }
  }

  bool Success = true;
  if (Args.Verify) {
    if (!Args.VerifyNumThreads)
      parallel::strategy =
          hardware_concurrency(hardware_concurrency().compute_thread_count());
    else
      parallel::strategy = hardware_concurrency(Args.VerifyNumThreads);
    for (StringRef Object : Objects)
      Success &= handleFile(
          Object,
          [&Args](ObjectFile &Obj, DWARFContext &DICtx, const Twine &Filename,
                  raw_ostream &OS) {
            return verifyObjectFile(Obj, DICtx, Filename, OS, Args);
          },
          OutputFile.os(), Args.ArchFilters, Args.ManuallyGenerateUnitIndex);
  } else if (Args.Statistics) {
    for (StringRef Object : Objects)
      Success &= handleFile(Object, collectStatsForObjectFile, OutputFile.os(),
                            Args.ArchFilters, Args.ManuallyGenerateUnitIndex);
  } else if (Args.ShowSectionSizes) {
    for (StringRef Object : Objects)
      Success &= handleFile(Object, collectObjectSectionSizes, OutputFile.os(),
                            Args.ArchFilters, Args.ManuallyGenerateUnitIndex);
  } else if (Args.ShowSources) {
    for (StringRef Object : Objects)
      Success &= handleFile(Object, collectObjectSources, OutputFile.os(),
                            Args.ArchFilters, Args.ManuallyGenerateUnitIndex);
  } else {
    for (StringRef Object : Objects)
      Success &= handleFile(
          Object,
          [&Args](ObjectFile &Obj, DWARFContext &DICtx, const Twine &Filename,
                  raw_ostream &OS) {
            return dumpObjectFile(Obj, DICtx, Filename, OS, Args);
          },
          OutputFile.os(), Args.ArchFilters, Args.ManuallyGenerateUnitIndex);
  }

  if (!Args.CoverageBaseline.empty()) {
    auto handleBaseline = [&](ObjectFile &BaselineObj,
                              DWARFContext &BaselineCtx, const Twine &Filename,
                              raw_ostream &OS) {
      auto showCoverage = [&](ObjectFile &Obj, DWARFContext &DICtx,
                              const Twine &Filename, raw_ostream &OS) {
        return showVariableCoverage(Obj, DICtx, &BaselineObj, &BaselineCtx,
                                    Args.BitcodeFile, Args.CombineInstances,
                                    OS);
      };
      for (StringRef Object : Objects)
        Success &= handleFile(Object, showCoverage, OutputFile.os(),
                              Args.ArchFilters, Args.ManuallyGenerateUnitIndex);
      return true;
    };
    Success &=
        handleFile(Args.CoverageBaseline, handleBaseline, OutputFile.os(),
                   Args.ArchFilters, Args.ManuallyGenerateUnitIndex);
  } else if (Args.ShowVariableCoverage || !Args.BitcodeFile.empty()) {
    auto showCoverage = [&](ObjectFile &Obj, DWARFContext &DICtx,
                            const Twine &Filename, raw_ostream &OS) {
      return showVariableCoverage(Obj, DICtx, nullptr, nullptr,
                                  Args.BitcodeFile, Args.CombineInstances, OS);
    };
    for (StringRef Object : Objects)
      Success &= handleFile(Object, showCoverage, OutputFile.os(),
                            Args.ArchFilters, Args.ManuallyGenerateUnitIndex);
  }

  return Success ? EXIT_SUCCESS : EXIT_FAILURE;
}
