//===- ColorOptions.h - `--color` output option -----------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// llvm::ColorOptions: a hand-written options struct for `--color`/`-color`
// (bare, or Joined `=<value>`). Like llvm::PluginLoaderOptions, this cannot
// be generated by -gen-opt-parser-defs: that mechanism is built on
// llvm::opt::OptTable/Arg/ArgList (LLVMOption), and llvm/lib/Option links
// Support (see llvm/lib/Option/CMakeLists.txt's LINK_COMPONENTS), so Support
// cannot link Option back without a cycle -- and this struct must live in
// lib/Support, next to WithColor.cpp. It exposes the exact same
// `parse(Args, Rest, Errs)` signature a generated struct does, so it composes
// with llvm::opt::parseLibraryOptionsChain (see
// llvm/include/llvm/Option/LibraryOptions.h) like any other library options
// struct, but has no Slot/table()/apply()/RegisterLibraryOptions<T> -- those
// only matter for LLVMContext::getOptions<T>() integration. `--color` is
// deliberately a process-wide global, not context-scoped: see the NOTE in
// WithColor.cpp for why.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_SUPPORT_COLOROPTIONS_H
#define LLVM_SUPPORT_COLOROPTIONS_H

#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/BoolOrDefault.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/raw_ostream.h"

namespace llvm {

struct ColorOptions {
  cl::boolOrDefault Color = cl::boolOrDefault::BOU_UNSET;

  LLVM_ABI static ColorOptions Current;

  LLVM_ABI llvm::Error parse(llvm::ArrayRef<const char *> Args,
                              llvm::SmallVectorImpl<const char *> &Rest,
                              llvm::raw_ostream &Errs);
};

} // namespace llvm

#endif // LLVM_SUPPORT_COLOROPTIONS_H
