//===- SupportOptions.h - LLVMSupport library options -----------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// llvm::SupportOptions: a hand-written options struct for LLVMSupport's own
// flags (-stats, -debug, -debug-only, -debug-counter, -info-output-file,
// -rng-seed, ...). Like llvm::PluginLoaderOptions and llvm::ColorOptions, it
// cannot be generated by -gen-opt-parser-defs: llvm/lib/Option links Support,
// so Support cannot link Option back. It exposes the same
// `parse(Args, Rest, Errs)` signature a generated struct does, so it composes
// with llvm::opt::parseLibraryOptionsChain.
//
// Unlike a generated struct, parse() does not keep what it parsed: it writes
// each option it saw straight into the process-wide state that option
// configures (DebugFlag, the DebugCounter singleton, Timer's output file, the
// globals below, ...) before returning, and leaves every option that was not
// given untouched. Keeping the values instead would need a static member that
// owns std::string/std::vector storage, which llvm/lib/Support's
// -Werror=global-constructors rejects (a global destructor). -rng-seed is the
// one option read back later, so it is the one field kept here.
//
// Tools still parsing through clv2 reach the same state through
// support::applySupportOptions(), declared in SupportOptionsOptInfos.h.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_SUPPORT_SUPPORTOPTIONS_H
#define LLVM_SUPPORT_SUPPORTOPTIONS_H

#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/raw_ostream.h"
#include <cstdint>

namespace llvm {

struct SupportOptions {
  /// -rng-seed=<seed>, read by Module::createRNG(). 0 means unseeded.
  uint64_t RngSeed = 0;

  LLVM_ABI static SupportOptions Current;

  LLVM_ABI llvm::Error parse(llvm::ArrayRef<const char *> Args,
                              llvm::SmallVectorImpl<const char *> &Rest,
                              llvm::raw_ostream &Errs);
};

namespace support {

LLVM_ABI extern bool StatsEnabled;
LLVM_ABI extern bool StatsAsJsonEnabled;
LLVM_ABI extern unsigned DebugBufferSizeVal;
LLVM_ABI extern bool ViewBackgroundFlag;
/// Directory for -dot-file-location, or empty for a temporary file.  A
/// StringRef rather than a std::string: llvm/lib/Support is built with
/// -Werror=global-constructors, which a namespace-scope std::string violates.
/// SupportOptions.cpp owns the characters.
LLVM_ABI extern StringRef DagFileLocation;
LLVM_ABI extern bool NoOpenDagViewer;

} // namespace support
} // namespace llvm

#endif // LLVM_SUPPORT_SUPPORTOPTIONS_H
